/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LinkDevice: typeof import('./src/components/LinkDevice.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NFlex: typeof import('naive-ui')['NFlex']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Page: typeof import('./src/components/Page.vue')['default']
  }
}
